import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import { Sidebar } from "@/components/sidebar";
import { Header } from "@/components/header";

import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark h-full">
      <body
        className={`${inter.variable} ${geistMono.variable} h-full antialiased`}
      >
        <Header />
        <div className="flex min-h-full gap-4 bg-background">
          <Sidebar />
          <div className="ml-[320px] mt-16 w-full">
            <div className="h-full min-h-full w-full border-l bg-background">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
