import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark h-full">
      <body
        className={`${inter.variable} ${geistMono.variable} h-full antialiased`}
      >
        <section className="fixed left-0 top-0 z-50 h-16 w-full border-b border-border bg-background px-12">
          <div className="max-w-[1240px]">
            Add Tilting point logo and game selector
          </div>
        </section>
        <div className="flex min-h-full gap-4 bg-background">
          <Sidebar />
          <div className="ml-[320px] mt-16 w-full">
            <div className="h-full min-h-full w-full border-l border-border bg-background">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
